src/Entity/Entreprise.php
<?php

namespace App\Entity;

use App\Repository\EntrepriseRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EntrepriseRepository::class)]
class Entreprise
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 60, nullable: true)]
    private $Designation;

    #[ORM\OneToMany(mappedBy: 'Entreprise', targetEntity: PFE::class)]
    private $pFEs;

    public function __construct()
    {
        $this->pFEs = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDesignation(): ?string
    {
        return $this->Designation;
    }

    public function setDesignation(?string $Designation): self
    {
        $this->Designation = $Designation;

        return $this;
    }
    public function __toString()
    {
        return $this->Designation;
    }

    /**
     * @return Collection<int, PFE>
     */
    public function getPFEs(): Collection
    {
        return $this->pFEs;
    }

    public function addPFE(PFE $pFE): self
    {
        if (!$this->pFEs->contains($pFE)) {
            $this->pFEs[] = $pFE;
            $pFE->setEntreprise($this);
        }

        return $this;
    }

    public function removePFE(PFE $pFE): self
    {
        if ($this->pFEs->removeElement($pFE)) {
            // set the owning side to null (unless already changed)
            if ($pFE->getEntreprise() === $this) {
                $pFE->setEntreprise(null);
            }
        }

        return $this;
    }
}

src/Entity/PFE.php
<?php

namespace App\Entity;

use App\Repository\PFERepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PFERepository::class)]
class PFE
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 58)]
    private $Title;

    #[ORM\Column(type: 'string', length: 50, nullable: true)]
    private $NomStudent;

    #[ORM\ManyToOne(targetEntity: Entreprise::class, inversedBy: 'pFEs')]
    #[ORM\JoinColumn(nullable: false)]
    private $entreprise;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->Title;
    }

    public function setTitle(string $Title): self
    {
        $this->Title = $Title;

        return $this;
    }

    public function getNomStudent(): ?string
    {
        return $this->NomStudent;
    }

    public function setNomStudent(?string $NomStudent): self
    {
        $this->NomStudent = $NomStudent;

        return $this;
    }

    public function getEntreprise(): ?Entreprise
    {
        return $this->entreprise;
    }

    public function setEntreprise(?Entreprise $entreprise): self
    {
        $this->entreprise = $entreprise;

        return $this;
    }
}

src/Form/PFEType.php
<?php

namespace App\Form;

use App\Entity\PFE;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PFEType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('Title')
            ->add('NomStudent')
            ->add('Entreprise')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => PFE::class,
        ]);
    }
}

src/Controller/AddPFEController.php
<?php

namespace App\Controller;

use App\Entity\PFE;
use App\Form\PFEType;

use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;


class AddPFEController extends AbstractController
{
    #[Route('/add/', name: 'app_add_p_f_e')]
    public function index(ManagerRegistry $doctrine, Request $request): Response {
        $entityManager = $doctrine->getManager();

        $pfe = new PFE();
        $form = $this->createForm(PFEType::class, $pfe);

        $form->handleRequest($request);
        if ($form->isSubmitted()) {
            $entityManager->persist($pfe);
            $entityManager->flush();
            return $this->render('pfe.info.html.twig',['pfe' => $pfe]);
        } else {
            return $this->render('add_pfe/index.html.twig', [
                'form' => $form->createView()
            ]);
        }

    }
}

src/Controller/AfficheController.php
<?php

namespace App\Controller;

use App\Entity\Entreprise;
use App\Entity\PFE;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Config\Framework\WebLinkConfig;

class AfficheController extends AbstractController
{

    #[Route('/stats', name: 'app_stats')]
    public function index(ManagerRegistry $doctrine,): Response {
        $repo = $doctrine->getRepository(PFE::class);
        $PFEparEntreprise = $repo->countPFE();

        return $this->render('stats/index.html.twig', [
            'PFEparEntreprise' => $PFEparEntreprise
        ]);
    }
    #[Route('/all', name: 'app_all')]
    public function afficheAll(ManagerRegistry $doctrine,): Response {
        $repo = $doctrine->getRepository(PFE::class);
        $allPFE = $repo->findAll();

        return $this->render('all/index.html.twig', [
            'listePFE' => $allPFE
        ]);
    }



}

templates/add_pfe/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajout d'une PFE{% endblock %}

{% block PageTitle %} Remplir le formulaire pour ajouter une PFE{% endblock %}

{% block body %}
   {{ form_start(form)}}
    {{ form_rest(form) }}
    <div class="row">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
{% endblock %}

templates/all/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des PFEs{% endblock %}
{% block PageTitle %}
    Liste des PFEs
{% endblock %}
{% block body %}
    <div class="row">
        {% for PFE in listePFE %}
            <div class="card text-white bg-{% if(loop.index is odd) %}primary{% else %}success{% endif %} m-2 col-3"
                 style="max-width: 18rem;">
                <div class="card-header">{{ PFE.title }}</div>
                <div class="card-body">
                    <h5 class="card-title"> Etudiant : {{ PFE.nomStudent }}</h5>
                    <p class="card-text">Entreprise : {{ PFE.entreprise }}</p>

                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

templates/base.html.twig
<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
    
        <link rel="stylesheet" href="/node_modules/bootstrap/dist/css/bootstrap.min.css">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous"
    
</head>
<body>
<div class="container">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">TP</a>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-link" aria-current="page" href="{{ path('app_all') }}">Liste des PFEs</a>
                    <a class="nav-link" href="{{ path('app_add_p_f_e') }}">Ajouter un PFE</a>
                    <a class="nav-link" href="{{ path('app_stats') }}">Stats</a>
                </div>
            </div>
        </div>
    </nav>
    <div class="alert alert-info mt-4 mb-4" role="alert">
        {% block PageTitle %}
            Placeholder
        {% endblock %}
    </div>
    {% block body %}

    {% endblock %}
</div>


    <script src="{{ asset('node_modules/bootstrap/dist/js/bootstrap.min.js') }}"></script>
    <script src="{{ asset('node_modules/@popperjs/core/dist/umd/popper.min.js') }}"></script>

</body>
</html>

templates/pfe.info.html.twig
{% extends 'base.html.twig' %}
{% block title %} Ajout avec succés! {% endblock %}

{% block PageTitle %} Le PFE a été ajouté avec succés{% endblock %}

{% block body %}
    <h1> Titre du PFE : {{ pfe.title }}</h1>
    <h2>Nom du l'étudiant : {{ pfe.nomStudent }}</h2>
    <h2>Entreprise: {{ pfe.entreprise }}</h2>
{% endblock %}

templates/stats/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}liste de PFE par Entreprise{% endblock %}
{% block PageTitle %}
    Nombres de PFE par entreprises
{% endblock %}
{% block body %}
    <div class="row">
    {% for entreprise in PFEparEntreprise %}
        <div class="card text-white bg-{%if(loop.index is odd)%}primary{% else %}success{% endif %} m-2 col-3" style="max-width: 18rem;">
            <div class="card-header">{{ entreprise['Designation'] }}</div>
            <div class="card-body">
                <h5 class="card-title">{{ entreprise[1] }} Pfe(s)</h5>
            </div>
        </div>
    {% endfor %}
    </div>
{% endblock %}